/**
 * CV Crafter Agent (Agent 2)
 * 
 * Autonomous AI agent that:
 * - Generates tailored CVs for specific job applications
 * - Creates cover letters optimized for each role
 * - Analyzes skill gaps between user profile and job requirements
 * - Stores generated documents in generated_cvs and cover_letters tables
 */

import { LLMProviderManager, LLMProvider } from "./llm-providers.js";
import { JobDatabaseClient } from "./job-database-client.js";

export interface CVCrafterConfig {
	name: string;
	agentId: string;
	databaseUrl: string;
	llmProvider: LLMProvider;
	llmApiKey?: string;
	llmModel?: string;
	targetUserId: string; // User to create CVs for
}

export class CVCrafterAgent {
	private config: CVCrafterConfig;
	private dbClient: JobDatabaseClient;
	private llmManager: LLMProviderManager;
	private isConnected: boolean = false;

	constructor(config: CVCrafterConfig, llmManager: LLMProviderManager) {
		this.config = config;
		this.dbClient = new JobDatabaseClient(config.databaseUrl);
		this.llmManager = llmManager;
	}

	/**
	 * Connect to the database
	 */
	async connect(): Promise<void> {
		try {
			console.log(`Agent ${this.config.name} (${this.config.agentId}) connecting...`);
			await this.dbClient.connect();
			this.isConnected = true;
			console.log(`Agent ${this.config.name} connected!`);
		} catch (error) {
			console.error(`Failed to connect agent ${this.config.name}:`, error);
			throw error;
		}
	}

	/**
	 * Disconnect from the database
	 */
	async disconnect(): Promise<void> {
		this.isConnected = false;
		await this.dbClient.disconnect();
		console.log(`Agent ${this.config.name} disconnected`);
	}

	/**
	 * Agent's iteration: Generate CVs and cover letters for draft applications
	 */
	async takeTurn(iteration: number): Promise<void> {
		console.log(`\n📝 ${this.config.name} (${this.config.llmProvider}) - Turn ${iteration}`);

		try {
			// 1. Find applications with status='draft'
			const draftApplications = await this.dbClient.getApplications(this.config.targetUserId, "draft");
			console.log(`  📋 Found ${draftApplications.length} draft application(s)`);

			if (draftApplications.length === 0) {
				console.log(`  ⚠️  No draft applications found, skipping turn`);
				return;
			}

			// 2. Get user profile
			const userProfile = await this.dbClient.getUserProfile(this.config.targetUserId);
			if (!userProfile) {
				console.log(`  ⚠️  User profile not found`);
				return;
			}

			// 3. Process each draft application
			for (const application of draftApplications) {
				try {
					console.log(`  🔨 Processing application #${application.id} for: ${application.job_title}`);

					// Get job details
					const job = await this.dbClient.getJobById(application.job_id);
					if (!job) {
						console.log(`  ⚠️  Job ${application.job_id} not found, skipping`);
						continue;
					}

					// 4. Generate tailored CV using LLM
					console.log(`  ✨ Generating tailored CV...`);
					const cvResult = await this.llmManager.generateCV(
						this.config.llmProvider,
						this.config.llmModel || "default",
						userProfile,
						job
					);

					const savedCV = await this.dbClient.saveCV(
						this.config.targetUserId,
						application.job_id,
						cvResult.content,
						cvResult.format
					);
					console.log(`  ✅ CV generated (version ${savedCV.version})`);

					// 5. Generate cover letter using LLM
					console.log(`  ✨ Generating cover letter...`);
					const coverLetterResult = await this.llmManager.generateCoverLetter(
						this.config.llmProvider,
						this.config.llmModel || "default",
						userProfile,
						job,
						"professional"
					);

					const savedCoverLetter = await this.dbClient.saveCoverLetter(
						this.config.targetUserId,
						application.job_id,
						coverLetterResult.content,
						coverLetterResult.tone
					);
					console.log(`  ✅ Cover letter generated (version ${savedCoverLetter.version})`);

					// 6. Analyze skill gaps
					await this.analyzeSkillGaps(userProfile, job);

					// 7. Update application status to 'ready_to_submit'
					await this.dbClient.updateApplicationStatus(
						application.id,
						"ready_to_submit",
						`CV and cover letter generated by ${this.config.name}`
					);
					console.log(`  ✅ Application status updated to 'ready_to_submit'`);
				} catch (error) {
					console.error(`  ❌ Error processing application ${application.id}:`, error);
					continue;
				}
			}

			console.log(`  ✅ Turn complete! Processed ${draftApplications.length} application(s)`);
		} catch (error) {
			console.error(`  ❌ Error in turn:`, error);
		}
	}

	/**
	 * Analyze skill gaps between user profile and job requirements
	 */
	private async analyzeSkillGaps(userProfile: any, job: any): Promise<void> {
		try {
			const userSkills = new Set(
				userProfile.skills?.map((s: any) => s.skill_name.toLowerCase()) || []
			);
			const requiredSkills = (job.required_skills || []).map((s: string) => s.toLowerCase());
			const preferredSkills = (job.preferred_skills || []).map((s: string) => s.toLowerCase());

			const missingRequired = requiredSkills.filter((skill) => !userSkills.has(skill));
			const missingPreferred = preferredSkills.filter((skill) => !userSkills.has(skill));

			if (missingRequired.length > 0 || missingPreferred.length > 0) {
				const insightDescription = `Skill Gap Analysis for ${job.title}:
Missing Required Skills: ${missingRequired.join(", ") || "None"}
Missing Preferred Skills: ${missingPreferred.join(", ") || "None"}
Recommendation: Consider learning these skills to improve match.`;

				await this.dbClient.addInsight(
					this.config.agentId,
					this.config.targetUserId,
					"skill_gap",
					insightDescription,
					{
						job_id: job.id,
						job_title: job.title,
						missing_required: missingRequired,
						missing_preferred: missingPreferred,
					}
				);

				console.log(`  📊 Skill gap analysis completed`);
			}
		} catch (error) {
			console.error(`  ⚠️  Error analyzing skill gaps:`, error);
		}
	}
}

