import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { Props, createErrorResponse, createSuccessResponse } from "../types";
import { withDatabase } from "../database/utils";
import { formatDatabaseError } from "../database/security";

export function registerInsightsTools(server: McpServer, env: Env, props: Props) {
	// Get agent insights
	server.tool(
		"getAgentInsights",
		"Get insights generated by agents for a user, optionally filtered by agent or insight type.",
		{
			user_id: z.string().describe("User ID"),
			agent_id: z.string().optional().describe("Filter by agent ID"),
			insight_type: z.string().optional().describe("Filter by insight type"),
			is_read: z.boolean().optional().describe("Filter by read status"),
			limit: z.number().int().min(1).max(100).optional().default(50).describe("Maximum number of results"),
		},
		async ({ user_id, agent_id, insight_type, is_read, limit = 50 }) => {
			try {
				return await withDatabase((env as any).DATABASE_URL, async (db) => {
					let query = `SELECT * FROM agent_insights WHERE user_id = $1`;
					const values: any[] = [user_id];
					let paramIndex = 2;
					
					if (agent_id) {
						query += ` AND agent_id = $${paramIndex++}`;
						values.push(agent_id);
					}
					if (insight_type) {
						query += ` AND insight_type = $${paramIndex++}`;
						values.push(insight_type);
					}
					if (is_read !== undefined) {
						query += ` AND is_read = $${paramIndex++}`;
						values.push(is_read);
					}
					
					query += ` ORDER BY created_at DESC LIMIT $${paramIndex}`;
					values.push(limit);
					
					const insights = await db.unsafe(query, values);
					
					return createSuccessResponse(`Found ${insights.length} insight(s)`, insights);
				});
			} catch (error) {
				console.error('getAgentInsights error:', error);
				return createErrorResponse(`Error retrieving insights: ${formatDatabaseError(error)}`);
			}
		}
	);

	// Add insight (typically done by agents)
	const ALLOWED_USERNAMES = new Set<string>([
		'coleam00'
	]);

	if (ALLOWED_USERNAMES.has(props.login)) {
		server.tool(
			"addInsight",
			"Add an insight generated by an agent. Typically called by agents to store their analysis.",
			{
				agent_id: z.string().describe("Agent ID (e.g., 'job_hunter', 'cv_crafter', 'application_tracker')"),
				user_id: z.string().describe("User ID"),
				insight_type: z.string().describe("Type of insight (e.g., 'market_trend', 'skill_gap', 'application_pattern')"),
				description: z.string().describe("Description of the insight"),
				metadata: z.record(z.any()).optional().describe("Additional metadata as JSON object"),
			},
			async ({ agent_id, user_id, insight_type, description, metadata }) => {
				try {
					return await withDatabase((env as any).DATABASE_URL, async (db) => {
						await db.unsafe(
							`INSERT INTO agent_insights (agent_id, user_id, insight_type, description, metadata)
							 VALUES ($1, $2, $3, $4, $5::jsonb)`,
							[agent_id, user_id, insight_type, description, metadata ? JSON.stringify(metadata) : null]
						);
						
						return createSuccessResponse("Insight added successfully");
					});
				} catch (error) {
					console.error('addInsight error:', error);
					return createErrorResponse(`Error adding insight: ${formatDatabaseError(error)}`);
				}
			}
		);

		server.tool(
			"markInsightAsRead",
			"Mark an insight as read or unread.",
			{
				insight_id: z.number().int().describe("Insight ID"),
				is_read: z.boolean().describe("Whether the insight is read"),
			},
			async ({ insight_id, is_read }) => {
				try {
					return await withDatabase((env as any).DATABASE_URL, async (db) => {
						await db.unsafe(
							`UPDATE agent_insights SET is_read = $1 WHERE id = $2`,
							[is_read, insight_id]
						);
						
						return createSuccessResponse(`Insight marked as ${is_read ? 'read' : 'unread'}`);
					});
				} catch (error) {
					console.error('markInsightAsRead error:', error);
					return createErrorResponse(`Error updating insight: ${formatDatabaseError(error)}`);
				}
			}
		);
	}
}

